apiVersion: v1
name: onos-proxy
version: 0.1.0
kubeVersion: ">=1.10.0"
appVersion: 1.15.0-SNAPSHOT
description: ONOS proxy cluster
keywords:
- onos
- sdn
- networking
home: http://onosproject.org
icon: https://github.com/opennetworkinglab/onos/blob/master/tools/package/maven-plugin/src/main/resources/org/onosproject/maven/icon.png?raw=true
maintainers:
  - name: Jordan Halterman
    email: jordan@opennetworking.org
